version: "3.7"
services:
  games:
    container_name: games.netsoc.local
    image: uccnetsoc/games-panel:dev-env
    entrypoint: sh -c "/bin/ash docker/entrypoint-dev.sh"
    ports:
      - 8888:80
      - 8443:443
    depends_on:
      - mysql
      - games-daemon
      - phpmyadmin
      - proxy
      - keycloak
    environment:
      - APP_ENV=development
      - APP_THEME=netsoc
      - DB_HOST=mysql.netsoc.local
      - DB_PASSWORD=password
      - CURRENT_USER=${USER}
      - KEYCLOAK_CLIENT_ID=games
      - KEYCLOAK_CLIENT_SECRET=cc08716d-eafd-4102-aa04-44a29ba99e9f
      - KEYCLOAK_REDIRECT_URI=http://games.netsoc.local/auth/oauth/callback
      - KEYCLOAK_BASE_URL=http://keycloak.netsoc.local:8080/auth
      - KEYCLOAK_REALMS=freeipa
      - SERVER_MEMORY=2000
      - SERVER_SWAP=2000
      - DISK_SPACE=4000
      - SERVER_IO=500
      - SERVER_CPU=400
      - SERVER_THREADS=6
