version: "3.7"
services:
  games.netsoc.local:
    image: uccnetsoc/games-panel:dev-env
    ports:
      - 8888:80
      - 8443:443
    depends_on:
      - mysql.netsoc.local
      - proxy.netsoc.local
    environment:
      - APP_ENV=development
      - APP_THEME=netsoc
      - DB_HOST=mysql.netsoc.local
      - DB_PASSWORD=password
    volumes:
      - /app/resources/styles
      - /app/var
  mysql.netsoc.local:
    volumes:
      - ../games/data:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_USER=pterodactyl
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=panel
      - MYSQL_ROOT_PASSWORD=password
