version: "3.7"
services:
  games:
    container_name: games.netsoc.local
    image: uccnetsoc/games-panel:dev-env
    ports:
      - 8888:80
      - 8443:443
    depends_on:
      - mysql
      - proxy
    environment:
      - APP_ENV=development
      - APP_THEME=netsoc
      - DB_HOST=mysql.netsoc.local
      - DB_PASSWORD=password
    volumes:
      - /app/resources/styles
      - /app/var
