version: "3.7"
services:
  games:
    image: uccnetsoc/games-panel:dev-env
    ports:
      - 8888:80
      - 8443:443
    depends_on:
      - db
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.games.rule=Host(`games.netsoc.local`)"
      - "traefik.http.services.games-service.loadbalancer.server.port=80"
      - "traefik.http.routers.games.service=games-service"
    container_name: games
    environment:
      - APP_ENV=development
      - APP_THEME=netsoc
      - DB_HOST=netsoc-mysql
      - DB_PASSWORD=password
    volumes:
      - /app/resources/styles
      - /app/var
  db:
    volumes:
      - ../games/data:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_USER=pterodactyl
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=panel
      - MYSQL_ROOT_PASSWORD=password
