#!/bin/bash

docker-compose -f ./backing-services/docker-compose.yml $(find . -name 'docker-compose.*yml' -print0 | sort -rz | xargs -r0 -n 1 echo '-f' | grep -v 'backing-services' | xargs echo) ${@:1}
