version: "3.7"
services:
  discord-bot:
    image: uccnetsoc/discord-bot:dev-env
    container_name: discordbot
    command: modd # Hot reloading
    depends_on:
      - consul
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.discord-bot.rule=Host(`events.netsoc.local`)"
      - "traefik.http.services.discord-bot-service.loadbalancer.server.port=80"
      - "traefik.http.routers.discord-bot.service=discord-bot-service"
    ports:
      - 8888:80
    ## Vars to put in override:
    environment:
      - DISCORD_TOKEN=insert
      - TWITTER_KEY=insert
      - TWITTER_SECRET=insert
      - TWITTER_ACCESS_KEY=insert
      - TWITTER_ACCESS_SECRET=insert
      - CONSUL_ADDRESS=consul:8500
    volumes:
      - /bot
