version: "3.7"
services:
  discord-bot:
    image: uccnetsoc/discord-bot:dev-env
    container_name: discordbot
    command: modd # Hot reloading
    depends_on:
      - consul
      - prometheus
    ports:
      - 8888:80
    ## Vars to put in override:
    environment:
      - DISCORD_TOKEN=insert
      - TWITTER_KEY=insert
      - TWITTER_SECRET=insert
      - TWITTER_ACCESS_KEY=insert
      - TWITTER_ACCESS_SECRET=insert
      - CONSUL_ADDRESS=consul:8500
    volumes:
      - /bot
