version: "3.7"
services:
  discord-bot:
    image: docker.netsoc.co/public/discord-bot:dev-env
    container_name: discordbot
    ## Vars to put in override:
    # environment:
    #   - DISCORD_TOKEN
    volumes:
      - /bot
    command: modd # Hot reloading
    depends_on:
      - consul
