version: "3.7"
services:
  discord-bot:
    container_name: discord-bot.netsoc.local
    image: uccnetsoc/discord-bot:dev-env
    command: modd # Hot reloading
    depends_on:
      - prometheus
      - postgres
    ports:
      - 8888:80
    ## Vars to put in override:
    environment:
      - DISCORD_TOKEN=insert
      - TWITTER_KEY=insert
      - TWITTER_SECRET=insert
      - TWITTER_ACCESS_KEY=insert
      - TWITTER_ACCESS_SECRET=insert
      - MINECRAFT_HOST=minecraft.netsoc.co:1194
    volumes:
      - /bot
