
- setup:
  when: "inventory_hostname == provisionee_host"

- include_tasks: "build-lxc-template.yml"
  loop: "{{ templates }}"
  loop_control:
    loop_var: "template"

- include_tasks: "build-vm-template.yml"
  loop: "{{ templates }}"
  loop_control:
    loop_var: "template"