version: "3.7"
services:
  admin:
    container_name: admin.netsoc.local
    image: uccnetsoc/admin:dev-env
    command: npm run serve
    volumes:
      - /app
    environment:
      VUE_APP_NETSOC_API_URL: "http://api.netsoc.local"
    depends_on:
      - api
      - proxy
      - unitproxy
      - unit
      - ipa
      - ipaclient
      - keycloak
      - mysql

  api:
    container_name: api.netsoc.local
    restart: always
    image: uccnetsoc/admin_api:dev-env
    volumes:
      - /app
      - /requirements.txt
      - /config.yml
      - ../backing-services/freeipa/home/users:/home/users:z
    command: /start-reload.sh --host 0.0.0.0 --port 8080
    environment:
      MODULE_NAME: "v1.main"
      VARIABLE_NAME: "api"
