version: "3.7"
services:
  whodis_api:
    container_name: api.whodis.netsoc.localhost
    image: uccnetsoc/whodis:dev-env
    command: modd
    environment:
      - API_TITLE="whodis API"
      - API_DESCRIPTION="API to authenticate/authorize discord users"
    ports:
      - 80:8080
    volumes:
      - /app
    depends_on:
      - proxy
