version: '3.7'
services:
  windlass:
    image: docker.netsoc.co/public/windlass:dev-env
    container_name: windlass
    ports:
      - 5051:8080
    depends_on:
      - db
      - auth
      - consul
      - vault
      - windlass-worker
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.windlass.rule=Host(`windlass.netsoc.localhost`)"
      - "traefik.http.services.windlass-service.loadbalancer.server.port=8080"
      - "traefik.http.routers.windlass.service=windlass-service"

  windlass-worker:
    image: docker.netsoc.co/public/windlass-worker:dev-env
    container_name: windlass-worker
    cap_add:
      - NET_ADMIN
    network_mode: host
    depends_on:
      - db
      - consul
      - vault
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.windlass-worker.rule=Host(`windlass-worker.netsoc.localhost`)"
      - "traefik.http.services.windlass-worker-service.loadbalancer.server.port=9786"
      - "traefik.http.routers.windlass-worker.service=windlass-worker-service"