version: "3.7"
services:
  windlass:
    image: uccnetsoc/windlass:dev-env
    container_name: windlass
    ports:
      - 5051:8080
    depends_on:
      - db
      - auth
      - consul
      - vault
      - windlass-worker

  windlass-worker:
    image: uccnetsoc/windlass-worker:dev-env
    container_name: windlass-worker
    cap_add:
      - NET_ADMIN
    network_mode: host
    depends_on:
      - db
      - consul
      - vault
