version: "3.7"
services:
  windlass:
    image: uccnetsoc/windlass:dev-env
    ports:
      - 5051:8080
    depends_on:
      - mysql
      - auth
      - consul
      - vault
      - windlass-worker

  windlass-worker:
    image: uccnetsoc/windlass-worker:dev-env
    cap_add:
      - NET_ADMIN
    network_mode: host
    depends_on:
      - mysql
      - consul
      - vault
