version: "3.7"
services:
  windlass.netsoc.local:
    image: uccnetsoc/windlass:dev-env
    ports:
      - 5051:8080
    depends_on:
      - mysql.netsoc.local
      - auth.netsoc.local
      - consul.netsoc.local
      - vault.netsoc.local
      - windlass-worker.netsoc.local

  windlass-worker.netsoc.local:
    image: uccnetsoc/windlass-worker:dev-env
    cap_add:
      - NET_ADMIN
    network_mode: host
    depends_on:
      - mysql.netsoc.local
      - consul.netsoc.local
      - vault.netsoc.local
