version: "3.7"
services:
  website:
    container_name: netsoc.local
    image: uccnetsoc/netsoc.co:dev-env
    command: npm start -- --port 80
    environment:
      - API_URL=http://discord-bot.netsoc.local
    volumes:
      - /app
